### ISSUE TITLE
list_xxz_term.datのi,j成分の順序

### ISSUE THREAD

**Issue by ryuikaneko** [QS-Cube/ED#1]
list_xxz_term.datのi,j成分の順序はi<jで指定する必要がある、という理解で正しいでしょうか？
state_lists.f90のj_flip_ni(i,j,n,NOD)が、i<jを仮定しているように見えるのですが。

**Comment by ueda1984** [comment]
list_xxz_term.datのi,j成分の順序はi<jで指定する必要は特にありません。
i > j となっている場合は input_parm.f90 の中で順序を入れ替える処理をしています。

XXZ型の相互作用は入れ替えに対して対称なので本操作で問題ありませんが、添え字の入れ替えに対して反対称な相互作用を自前で導入される場合は気をつけていただければと思います。

**Comment by ryuikaneko** [comment]
理解しました。
どうもありがとうございます。
